sources:
  - name: eco2mix_raw
    description: "Données brutes eco2mix sur la consommation et production d'énergie par région"
    meta:
      external_location: "models/data/eco2mix-regional-cons-def.parquet"
    tables:
      - name: regional_cons_def
        description: "Consommation et production d'énergie régionale définitive"

  - name: temperature_raw
    description: "Données brutes de température quotidienne par région"
    meta:
      external_location: "models/data/temperature-quotidienne-regionale.parquet"
    tables:
      - name: quotidienne_regionale
        description: "Température quotidienne par région"

  - name: eco2mix_temps_reel
    description: "Données temps réel eco2mix - mise à jour continue"
    meta:
      external_location: "models/data/eco2mix-regional-tr.parquet"
    tables:
      - name: regional_tr
        description: "Consommation et production d'énergie régionale en temps réel"